## ソースコードの構成

- mdのプレビューで見ると、壊れてしまう。

.
├── main.py
├── tests/
│   └── test_main.py
│   └── __init__.py
├── README.md
├── requirements.txt
└── .gitignore


## ソースコードの概要

fastAPIにより、RESTAPIを実装。pytestによりユニットテストを実装。

main.py：フィボナッチ数列を返す関数の実装および"/fib"エンドポイントでの動作を実装。

- フィボナッチ数列は、時間計算量O(n)、空間計算量O(1)の単純な実装となっている。再帰的な実装や一般項を用いた実装が考えられたが、再帰的な実装は時間計算量O(2^n)になること（メモ化再帰だと時間計算量、空間計算量ともにO(n)）、一般項を用いた実装は桁が大きくなるにつれ計算誤差が大きくなるため採用しなかった。

- "/fib"エンドポイントの実装は、validation（PositiveInt）によって実装することを考えていたが、エラーハンドリングによるメッセージの定形化（{
 "status": 400,
 "message": "Bad request."
}）を優先して、validation無しでの実装となっている。

tests/test_main.py：main.pyで実装した"/fib"エンドポイントでの動作を確認するユニットテスト。

- クエリパラメータnが存在しないことや、nが自然数で無いこと、nが4300桁を超過すること（そもそもDos攻撃を防ぐ目的のエラーであり、sys.set_int_max_str_digits() によって制限のなくすことは可能だが今回はやめておく。）をエラーと定め、ユニットテストを行っている。
- GET以外のメソッドでのアクセスや、"/fib"以外へのアクセスは、この課題では扱っていないと考えた。fastAPIがデフォルトのエラーハンドリングを行っていることを確認した後コメントアウトしている。


## local環境

- ローカルホストの実行：メインディレクトリに移動して、以下コマンド

$ uvicorn main:app --reload

- ユニットテストの実行：tests/ディレクトリに移動して、以下コマンド

$ pytest

